### ISSUE TITLE
Should we commit JS dependencies and built JS bundle?

### ISSUE THREAD

**Issue by shevron** [datopian/ckanext-blob-storage#24]
This CKAN extension bundles some modern ES6 code, and requires running `npm install && npm run build` to properly function after installation. This is unusual for CKAN extensions and causes some confusion during installation. 

One option to avoid this is to commit our build bundle to the repo. 

This means users will not need to do anything special on installation, but that every change to our JS source code or even worse, to any of our tree of npm dependencies, will require a commit.

**Comment by anuveyatsu** [comment]
@shevron I don't think it is an issue to build bundles, if it is documented in the installation section. If we decide to include build files, we should do it in the CI 🤔

**Comment by shevron** [comment]
@anuveyatsu I tend to agree that running `npm install && npm run build` is preferred to committing built JS bundles. That said, we've had cases of confusion around this, so I brought it up as a suggestion / for discussion. 

Of course, if we choose not to commit the bundle we should document this in the README as currently it is not documented. 

/cc @rufuspollock might have an opinion on this as well.

**Comment by rufuspollock** [comment]
FIXED. I think we have instructions now in README plus we are going to move the DataPub stuff out to ckanext-datapub soon.
